### ISSUE TITLE
Suggestion: Ability for Automatic/Periodic Export

### ISSUE THREAD

**Issue by MS07112** [AamuLumi/Rimworld-Diary#10]
It would be really helpful if there could be an option in the settings for all of the events of a day to be automatically exported on a regular basis (daily, every few days, etc. in game time) instead of having to manually export the logs/diary.

**Comment by AamuLumi** [comment]
Version 1.1.1 has been sent to Steam Workshop, it will be available soon.

Please take a look to the mod settings to enable the automatic export.

Have a nice day ! :)
