### ISSUE TITLE
RimWar compatibility

### ISSUE THREAD

**Issue by AnnLikki** [AamuLumi/Rimworld-Diary#15]
Hi! I am playing with RimWar and Diary together. If I leave the setting "log letters (events)" on, it logs hidden RimWar events as well, which there's a lot of. RimWar letters don't show up on the right, but in their own little window. It would be nice if you could make them not log into the diary. Thanks!
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/0e1544fa-4167-44c4-a0ce-146db6b68f3b)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/7daf4e30-f732-4770-a38d-28cb96ed17f4)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/b67cdbd1-6531-41bf-b40b-b676f9d853d7)

**Comment by AamuLumi** [comment]
Hey,

It seems RimWar is adding events directly in the Rimworld Events memory, and I use this memory to populate the Diary.
It feels more like an issue from RimWar (because they seem to spam the Events memory).

I suppose I have to add a patch to prevent RimWar of adding Events in the memory.

**Comment by AnnLikki** [comment]
> Hey,
> 
> It seems RimWar is adding events directly in the Rimworld Events memory, and I use this memory to populate the Diary. It feels more like an issue from RimWar (because they seem to spam the Events memory).
> 
> I suppose I have to add a patch to prevent RimWar of adding Events in the memory.

Maybe that's the issue. Also, I am not familiar with technical side of thing, but maybe RimWar's events have special indicator (besides colour), that could be used as a tag of not adding them to the log?

**Comment by AamuLumi** [comment]
I don't remember correctly how events are stored in Rimworld, so I'll take a look if there's something like this usable.
If not, I'll go with a good ol' patch.

**Comment by AamuLumi** [comment]
I found a way to remove some of the RimWar messages.
It should works with the spam of "Trade Event" messages (the hidden RimWar messages) while keeping other important messages from RimWar.

I'll release this in the 1.1.3 soon. Don't hesitate to reopen the issue if there's more to do on this problem when the version will be released.

**Comment by AnnLikki** [comment]
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/8f8e4d29-fa78-4e20-8993-39499e7b156a)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/8ea22ab6-6e8b-43d6-9c79-184d95478025)

**Comment by AamuLumi** [comment]
Okay so it didn't work on what I wanted.
I tried with other events than Trade Event (due to some problem to debug that), I'll try to do something on it.

**Comment by AamuLumi** [comment]
Okay I understood that you wanted I remove RimWar intern logs from automatic writing but not from logs. That was the mistake, the fix works correctly.
So I also remove the RimWar logs from the Diary logs.

The fix will be avaialble in the next release.
