### ISSUE TITLE
Error when exporting HTML with Progress Renderer

### ISSUE THREAD

**Issue by AnnLikki** [AamuLumi/Rimworld-Diary#16]
I am not sure if I am supposed to submit my issue here or elsewhere. I for some reason can't export an html file with pictures, it causes an error:
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/8357ed14-7d81-42e9-ba9d-25bc72a05bfb)
Here's PR's folder on the desktop:
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/ca37e4b1-e3c9-4f64-8068-ea28fac66c01)
Here's mod settings:
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/3353f1b1-5989-423f-82cf-29a6d8c805b6)
Here's what export generates (a proper html file, but pictures aren't there, seems like they do not export together with the file, no "img-0" etc in the vicinity of the html file):
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/803de070-bcae-4e62-bb16-57c6dd1963d9)

**Comment by AnnLikki** [comment]
Please let me know if I need to provide more feedback on the issue!

**Comment by AamuLumi** [comment]
Hey,

Normally, Diary keeps paths of generated images by ProgressRenderer, and use these paths to create copy of these images in the HTML export.
Did you move manually images or did you change the export path in ProgressRenderer ?

Thanks a lot :)

**Comment by AnnLikki** [comment]
> Hey,
> 
> Normally, Diary keeps paths of generated images by ProgressRenderer, and use these paths to create copy of these images in the HTML export. Did you move manually images or did you change the export path in ProgressRenderer ?
> 
> Thanks a lot :)

I use desktop folder as directory for PR (I believe it was a default setting)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/6971c4e6-9344-463a-ba62-71c3f806f7a5)

Also if it helps images it the Diary are showing correctly
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/b22fd9a7-aaee-4980-a1bd-ac6f13f2ed27)

**Comment by AamuLumi** [comment]
Okay that's pretty strange. I'll do some tests tomorrow to reproduce this behaviour.

Thanks for all these informations !

**Comment by AamuLumi** [comment]
Hey !

I did some tests with a similar configuration, and I was not able to reproduce the bug.
Diary shows images correctly, so this is not a problem of generated images paths not stored correctly.
HTML file is generated but export crashes, so I'm sure it's crashing when copying images to the exported folder.

I have to ask a stupid question : do you have enough space on your storage where you storing your exports ?
PR's images are pretty big, so I think it's a possibility.

If it's not that, you can enable the Rimworld dev mode in Settings > General > Development mode, and give me the content of your debug log after trying to export.

**Comment by AnnLikki** [comment]
> do you have enough space on your storage where you storing your exports ?

Yes, in fact, I do. PR's folder weights around 3-4 GB, and I have extra 60+ GB on the D disk, where I want to have my export (C disk has around 200 GB of free space). Also, previously I tried exporting the diary next or in the same directory as PR (in desktop folders), no luck.

> If it's not that, give me the content of your debug log after trying to export.
Here you go:
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/7abb22b9-ac6c-459a-befc-2f583762544a)

`System.IO.FileNotFoundException: C:\Users\likki\Desktop\manually\rimworld-jennifer-33185-5500-2-06-14.jpg does not exist
File name: 'C:\Users\likki\Desktop\manually\rimworld-jennifer-33185-5500-2-06-14.jpg'
`
Ohhh I see. It searches for manually taken pics, which I moved from "manual" to general since I wanted to scroll thru them together. Should I fix it manually (checking every error-causing file) or there's a better solution?

**Comment by AnnLikki** [comment]
But anyway there's a problem, could you help me figure out what's going on?
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/594daf51-c00f-4a66-b434-457bd2d7b82d)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/7c814dc0-518a-45fe-a29e-43174c0e88e3)

**Comment by AamuLumi** [comment]
I don't have prepared solution in Diary for this kind of problem, so yeah, you have to move back the screenshots to their origin.
If you see another problem after moving back the screenshots, don't hesitate to reopen the issue.

And with this problem fixed, I'll release the 1.1.3 version in the next hour. :)

**Comment by AamuLumi** [comment]
> But anyway there's a problem, could you help me figure out what's going on? ![image](https://user-images.githubusercontent.com/46577377/237945654-594daf51-c00f-4a66-b434-457bd2d7b82d.png) ![image](https://user-images.githubusercontent.com/46577377/237945703-7c814dc0-518a-45fe-a29e-43174c0e88e3.png)

It seems the original path was `...\Desktop\manually\...` and not `...\Desktop\jennifer\manually\...`.

**Comment by AnnLikki** [comment]
Ohhh. Maybe that. Because I mid-game changed settings of PR to have a subfolder so it doesn't trash my entire desktop... Now there's no way to update Diary's paths?

**Comment by AamuLumi** [comment]
Currently, no.
But I'll add a new feature to fix this (#18). I'll add this to the new version, so the new version will not be released now.

**Comment by AnnLikki** [comment]
I moved it and everything works. Thanks for helping me out! 
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/df70ddac-d110-4d01-ad13-1c9be9c8c731)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/abcf3cd5-5a8a-41c2-94e6-4f9d274c9f7d)

**Comment by AamuLumi** [comment]
Okay I'm changing my plan again.

I'll release a new version with your 3 fixes, and I'll add a configuration window in the next small update (don't have the time to do the feature that today).
