### ISSUE TITLE
Add event's description

### ISSUE THREAD

**Issue by AnnLikki** [AamuLumi/Rimworld-Diary#17]
It would be nice to be able to record event's desc as well. For example:
[12h] Quest Available: Deserter
*quest's description*
[13h] Mad Muffalo
Seems like these muffalo are mad

Thank you for your patience!

**Comment by AamuLumi** [comment]
Hey,

I will add a new filter in settings named "All (with event descriptions)" which will do this behaviour.

Thanks for your help to improve Diary ! :D

**Comment by AnnLikki** [comment]
Lovely! Thank you so much!

**Comment by AamuLumi** [comment]
I added a new setting in the mod. I prefered to add something independant from log filter, so it's just a checkbox to toggle.

![image](https://github.com/AamuLumi/Rimworld-Diary/assets/1839713/626daa37-f24a-488e-8f2e-880f41d8fdbf)

It will be available in the 1.1.3 when released.

**Comment by AnnLikki** [comment]
> I added a new setting in the mod. I prefered to add something independant from log filter, so it's just a checkbox to toggle.
Amazing! That's how I wanted I to be as well, thank you

**Comment by AnnLikki** [comment]
A couple of things I would have liked to change are:
1) Don't add an extra line between event and its desc like so, it helps with readability
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/60b0079b-9b41-451a-8c65-6c99283643a8)

2) Quest descriptions aren't added, only event ones, e.g. 
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/7da093c2-71a7-4e67-a87a-124654048a0b)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/d4c7a3a3-e225-4181-8e8a-cd598e934d70)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/08c2da67-d7ff-4cb8-8087-8077143afeb0)
When quest desc is 
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/185b704b-4183-472e-a83c-4aee6c9f1ff3)


Sorry all my screenshots are in Russian, hope it doesn't take away from their meaning!

**Comment by AamuLumi** [comment]
1. No problem, I'll change that
2. It seems Rimworld is not storing the full quest description in the old logs. I'll try to reproduce the problem to see if I can fix that.
