### ISSUE TITLE
Wrong order of days in HTML file

### ISSUE THREAD

**Issue by AnnLikki** [AamuLumi/Rimworld-Diary#19]
I am incredibly sorry for opening so many issues and not letting you live your best life. 
But here's a problem with exported file:
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/1f0e5cac-1838-440d-bbac-15ac15d01aa6)

Dates are in wrong order. Before PR started creating pictures, diary had only text entries, and those seem to be in wrong order, even tho in the game they are correct.
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/c91fb0f8-844f-43b5-9bb5-3f674f57bf82)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/b94b63ec-2e4c-4f87-8b50-6b11dab4c919)
![image](https://github.com/AamuLumi/Rimworld-Diary/assets/46577377/ce73fbef-98dc-4462-83a9-fc175c33a496)
etc

Is there something I'm missing?

**Comment by AamuLumi** [comment]
Ahah no problem ! :D 

Probably a bug I forget to fix, so it will be fixed.
