### ISSUE TITLE
[Feature Request] Integration with Progress Renderer

### ISSUE THREAD

**Issue by JokeNeverSoke** [AamuLumi/Rimworld-Diary#2]
First of all, really love the mod!

However, I've found it difficult to visualize progress when starting new construction projects e.g. Building ship/new killzone

Would it be possible to attach/link to the shots generated by [Progress Renderer](https://steamcommunity.com/sharedfiles/filedetails/?id=2010777010)?

**Comment by AamuLumi** [comment]
Hey,

I didn't know this mod exists, and it's a pretty good idea.
During the early development of the mod, I worked on capturing some screenshots and attaching it to the Diary, but my knowledge in Unity and Rimworld rendering method was not enough to achieve that.

I have to study the Progress Renderer code and testing some ideas to say if it's possible.

Until that, do you think you need to add multiple screenshots per day in the Diary or one each day at a specific hour is enough ?

**Comment by AamuLumi** [comment]
I worked on the feature, and I got this : 

![image](https://user-images.githubusercontent.com/1839713/202881269-31380012-7eb0-4082-ba8d-b0b0c65fb215.png)
![image](https://user-images.githubusercontent.com/1839713/202881270-fd00535b-0e50-4eb0-9a97-9567616492cf.png)

Each time Progress Renderer creates an image, it's linked with the Diary.
I added a view to see all images in the Diary.
You can zoom and move the image.

In my tests, I set Progress Renderer to capture the map each hour. So it draws the test colony at 10h and 11h.

Does it seem ok for you ?

**Comment by JokeNeverSoke** [comment]
That is really cool! Would the integration still work with other capture intervals (such as 1day/2days)? I usually do them on an hourly basis.

**Comment by AamuLumi** [comment]
Yes ! I let these settings to Progress Renderer, and Diary just receive created images and time them.

**Comment by AamuLumi** [comment]
The feature is now updated on Steam.

If you find some problem relative to the discussed feature, you can reopen this issue or create a new issue.

Love on you, and long life to your pawns.
